name: Build and Release Binaries

on:
  pull_request:
    types:
      - closed
    branches:
      - trunk
  push:
    branches:
      - trunk
      - feature/*
      
jobs:
  build-release-artifacts:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: darwin
            suffix: ''
          - os: ubuntu-20.04
            name: linux
            suffix: ''
          - os: windows-latest
            name: windows
            suffix: '.exe'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      PYTHON_VERSION: "3.12"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3.12 python3.12-venv python3.12-dev python3-pip \
            build-essential zip curl

          python3.12 -m pip install --no-cache-dir --upgrade pip
          python3.12 -m pip install --no-cache-dir pyinstaller -r tools/requirements.txt

      - name: Install dependencies (Non-Linux)
        if: matrix.os != 'ubuntu-20.04'
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install --no-cache-dir pyinstaller -r tools/requirements.txt

      - name: Build Executable
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-20.04" ]]; then
            python3.12 -m pyinstaller tools/devsecops_engine_tools/devsecops-engine-tools.spec
          else
            pyinstaller tools/devsecops_engine_tools/devsecops-engine-tools.spec
          fi

      - name: Test Executable (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: ./dist/devsecops-engine-tools${{ matrix.suffix }} --help

      - name: Zip Artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: tar.exe -a -c -f devsecops-engine-tools.zip dist\\devsecops-engine-tools${{ matrix.suffix }}

      - name: Test Executable (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: ./dist/devsecops-engine-tools${{ matrix.suffix }} --help

      - name: Zip Artifact (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: zip devsecops-engine-tools.zip dist/devsecops-engine-tools${{ matrix.suffix }}

      - name: Upload Artifact
        #if: startsWith(github.ref, 'refs/heads/trunk')
        uses: actions/upload-artifact@v4
        with:
          name: devsecops-engine-tools-${{ matrix.os }}
          path: dist/devsecops-engine-tools*